pytest_plugins = [
    "backend.api.tests.fixtures.core",
    "backend.auth.tests.fixtures.login_fixtures",
    "backend.auth.tests.fixtures.register_fixtures",
    "backend.core.tests.fixtures.core",
    "backend.task.tests.fixtures.task_fixtures",
    "backend.comment.tests.fixtures.comment_fixtures",
    "backend.rbac.tests.fixtures.rbac_fixtures",
    "backend.rbac.tests.fixtures.redis_fixtures",
    "backend.evaluation.tests.fixtures.evaluation_fixtures",
    "backend.team.tests.fixtures.team_fixtures",
    "backend.user.tests.fixtures.user_fixtures",
    "backend.meeting.tests.fixtures.meeting_fixtures",
    "backend.calendar.tests.fixtures.calendar_fixtures",
    "tests.fixtures.init_db_fixtures",
    "tests.fixtures.environment_fixtures",
]
