version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    shm_size: 1gb
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: postgres -c max_connections=500
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    container_name: adminer

#  backend:
#    build: .
#    restart: always
#    ports:
#      - "8000:8000"
#    container_name: backend_rbac
#    depends_on:
#      - db
#    env_file: .env
#    environment:
#      - POSTGRES_HOST=db
#    volumes:
#      - .:/app
volumes:
  postgres_data: