version: '3.8'

services:
  migration:
    build:
      context: ../             # Контекст сборки — корень проекта
      dockerfile: infra/Dockerfile
    container_name: migration
    env_file:
      - ../.env
    entrypoint: [ "/bin/bash", "/app/infra/entrypoint.sh" ]
    # Указываем alembic, где лежит его конфиг
    command: sh -c "alembic -c backend/alembic.ini upgrade head && python -m backend.core.database.init_db"
    volumes:
      - ../:/app

  backend:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    container_name: backend
    restart: always
    ports:
      - "${UVICORN_PORT}:${UVICORN_PORT}"
    env_file:
      - ../.env
    depends_on:
      migration:
        condition: service_completed_successfully
    volumes:
      - ../:/app
      - erp_logs_volume:/app/logs
    command: uvicorn backend.api.main:app --host ${UVICORN_HOST} --port "${UVICORN_PORT}" --reload

networks:
  default:
    name: erp_shared_network
    external: true

volumes:
  erp_logs_volume:
    external: true
    name: erp_logs_volume