"""add_invite_code

Revision ID: 0b0bb150f666
Revises: c9ab59aa1373
Create Date: 2026-05-19 18:22:51.077475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0bb150f666'
down_revision: Union[str, Sequence[str], None] = 'c9ab59aa1373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('invite_code', sa.String(length=6), nullable=False))
    op.create_index(op.f('ix_teams_invite_code'), 'teams', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_invite_code'), table_name='teams')
    op.drop_column('teams', 'invite_code')
    # ### end Alembic commands ###
