"""add_tasks

Revision ID: 4a619b3e3db4
Revises: 0b0bb150f666
Create Date: 2026-05-19 21:11:24.450028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a619b3e3db4'
down_revision: Union[str, Sequence[str], None] = '0b0bb150f666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False, comment='Название задачи'),
    sa.Column('description', sa.Text(), nullable=True, comment='Подробности задачи'),
    sa.Column('expire', sa.Date(), nullable=True, comment='Дедлайн'),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', name='taskstatus', native_enum=False, length=50), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('executor_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'done')", name='check_valid_status_name'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
