"""added meetings crud

Revision ID: 4e4484d955da
Revises: 401016f51a60
Create Date: 2026-06-03 20:08:07.290188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4484d955da'
down_revision: Union[str, Sequence[str], None] = '401016f51a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('status', sa.Enum('pending', 'in_process', 'ends', 'canceled', name='meetingstatus', native_enum=False, length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'status')
    # ### end Alembic commands ###
