"""добавил_индексы

Revision ID: 5f9a98033223
Revises: 4e4484d955da
Create Date: 2026-06-06 17:45:25.296960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f9a98033223'
down_revision: Union[str, Sequence[str], None] = '4e4484d955da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_rules', 'business_element_id',
               existing_type=sa.BIGINT(),
               comment='ID бизнес-сущности для назначения прав',
               existing_nullable=False)
    op.alter_column('access_rules', 'role_id',
               existing_type=sa.BIGINT(),
               comment='ID роли, для которой назначаются права доступа',
               existing_nullable=False)
    op.alter_column('access_rules', 'policies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Матрица прав доступа к элементам для ролей с учетом контекста',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_access_rules_business_element_id'), 'access_rules', ['business_element_id'], unique=False)
    op.create_index(op.f('ix_access_rules_role_id'), 'access_rules', ['role_id'], unique=False)
    op.alter_column('business_elements', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Название бизнес-сущности',
               existing_nullable=False)
    op.alter_column('comments', 'task_id',
               existing_type=sa.INTEGER(),
               comment='ID связанной задачи',
               existing_nullable=False)
    op.alter_column('comments', 'author_id',
               existing_type=sa.BIGINT(),
               comment='ID автора комментария',
               existing_nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата/время написания комментария',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.alter_column('evaluations', 'value',
               existing_type=sa.INTEGER(),
               comment='Оценка от 1 до 5',
               existing_nullable=False)
    op.alter_column('evaluations', 'comment',
               existing_type=sa.TEXT(),
               comment='Комментарий к оценке',
               existing_nullable=True)
    op.alter_column('evaluations', 'evaluator_id',
               existing_type=sa.BIGINT(),
               comment='ID руководителя, ставящего оценку',
               existing_nullable=True)
    op.alter_column('evaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата/время оценки',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_evaluations_evaluator_id'), 'evaluations', ['evaluator_id'], unique=False)
    op.alter_column('meetings', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Статус встречи',
               existing_nullable=False)
    op.alter_column('meetings', 'author_id',
               existing_type=sa.BIGINT(),
               comment='ID автора встречи',
               existing_nullable=True)
    op.create_index(op.f('ix_meetings_author_id'), 'meetings', ['author_id'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='Название роли',
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Статус задачи',
               existing_nullable=False)
    op.alter_column('tasks', 'author_id',
               existing_type=sa.BIGINT(),
               comment='ID автора задачи',
               existing_nullable=True)
    op.alter_column('tasks', 'executor_id',
               existing_type=sa.BIGINT(),
               comment='ID исполнителя задачи',
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата/время создания задачи',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_tasks_author_id'), 'tasks', ['author_id'], unique=False)
    op.create_index(op.f('ix_tasks_executor_id'), 'tasks', ['executor_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Название команды',
               existing_nullable=False)
    op.alter_column('teams', 'description',
               existing_type=sa.TEXT(),
               comment='Описание команды',
               existing_nullable=True)
    op.alter_column('teams', 'invite_code',
               existing_type=sa.VARCHAR(length=6),
               comment='Код приглашения в команду, генерируется автоматически',
               existing_nullable=False)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата создания команды',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_teams_invite_code'), table_name='teams')
    op.create_unique_constraint(None, 'teams', ['invite_code'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='Электронная почта/логин пользователя',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment='Зашифрованный хэшем пароль',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment='Имя пользователя',
               existing_nullable=False)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=30),
               comment='Отчество пользователя',
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=35),
               comment='Фамилия пользователя',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Статус активности (True/False)',
               existing_nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.BIGINT(),
               comment='ID роли пользователя',
               existing_nullable=False)
    op.alter_column('users', 'team_id',
               existing_type=sa.INTEGER(),
               comment='ID команды, в которой состоит пользователь',
               existing_nullable=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.alter_column('users', 'team_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID команды, в которой состоит пользователь',
               existing_nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID роли пользователя',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Статус активности (True/False)',
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=35),
               comment=None,
               existing_comment='Фамилия пользователя',
               existing_nullable=True)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Отчество пользователя',
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Имя пользователя',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Зашифрованный хэшем пароль',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Электронная почта/логин пользователя',
               existing_nullable=False)
    op.drop_constraint(None, 'teams', type_='unique')
    op.create_index(op.f('ix_teams_invite_code'), 'teams', ['invite_code'], unique=True)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата создания команды',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'invite_code',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='Код приглашения в команду, генерируется автоматически',
               existing_nullable=False)
    op.alter_column('teams', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание команды',
               existing_nullable=True)
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Название команды',
               existing_nullable=False)
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_executor_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_author_id'), table_name='tasks')
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата/время создания задачи',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'executor_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID исполнителя задачи',
               existing_nullable=True)
    op.alter_column('tasks', 'author_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID автора задачи',
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Статус задачи',
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Название роли',
               existing_nullable=False)
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_author_id'), table_name='meetings')
    op.alter_column('meetings', 'author_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID автора встречи',
               existing_nullable=True)
    op.alter_column('meetings', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Статус встречи',
               existing_nullable=False)
    op.drop_index(op.f('ix_evaluations_evaluator_id'), table_name='evaluations')
    op.alter_column('evaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата/время оценки',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('evaluations', 'evaluator_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID руководителя, ставящего оценку',
               existing_nullable=True)
    op.alter_column('evaluations', 'comment',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Комментарий к оценке',
               existing_nullable=True)
    op.alter_column('evaluations', 'value',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Оценка от 1 до 5',
               existing_nullable=False)
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата/время написания комментария',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('comments', 'author_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID автора комментария',
               existing_nullable=True)
    op.alter_column('comments', 'task_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID связанной задачи',
               existing_nullable=False)
    op.alter_column('business_elements', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Название бизнес-сущности',
               existing_nullable=False)
    op.drop_index(op.f('ix_access_rules_role_id'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_business_element_id'), table_name='access_rules')
    op.alter_column('access_rules', 'policies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Матрица прав доступа к элементам для ролей с учетом контекста',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('access_rules', 'role_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID роли, для которой назначаются права доступа',
               existing_nullable=False)
    op.alter_column('access_rules', 'business_element_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID бизнес-сущности для назначения прав',
               existing_nullable=False)
    # ### end Alembic commands ###
