"""add_logs

Revision ID: 6786b51d723e
Revises: 5f9a98033223
Create Date: 2026-07-15 17:42:27.664015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6786b51d723e'
down_revision: Union[str, Sequence[str], None] = '5f9a98033223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='ID пользователя'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Действие над сущностью'),
    sa.Column('entity_name', sa.String(length=50), nullable=False, comment='Название сущности'),
    sa.Column('entity_id', sa.Integer(), nullable=False, comment='ID сущности'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('tg_id', sa.BigInteger(), nullable=True, comment='ID пользователя в телеграме'))
    op.create_unique_constraint(None, 'users', ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'tg_id')
    op.drop_table('logs')
    # ### end Alembic commands ###
