"""init

Revision ID: c9ab59aa1373
Revises: 
Create Date: 2026-05-19 15:45:49.265594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ab59aa1373'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_elements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Enum('USER', 'ADMIN', 'MANAGER', name='rolename', native_enum=False, length=50), nullable=False),
    sa.CheckConstraint("name IN ('user', 'admin', 'manager')", name='check_valid_role_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('access_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_element_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('read_permission', sa.Boolean(), nullable=False),
    sa.Column('read_all_permission', sa.Boolean(), nullable=False),
    sa.Column('create_permission', sa.Boolean(), nullable=False),
    sa.Column('update_permission', sa.Boolean(), nullable=False),
    sa.Column('update_all_permission', sa.Boolean(), nullable=False),
    sa.Column('delete_permission', sa.Boolean(), nullable=False),
    sa.Column('delete_all_permission', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_element_id'], ['business_elements.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=35), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('access_rules')
    op.drop_table('teams')
    op.drop_table('roles')
    op.drop_table('business_elements')
    # ### end Alembic commands ###
